"""Tag table has id column now and the primary key is composite

Revision ID: 195fa476d19c
Revises: 6004a959d5e3
Create Date: 2025-01-24 13:18:18.473599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195fa476d19c'
down_revision: Union[str, None] = '6004a959d5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tags', 'users', ['id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'id')
    # ### end Alembic commands ###
