"""TaskStatus Enum Updated

Revision ID: 2323edcc8a4f
Revises: 195fa476d19c
Create Date: 2025-01-24 13:44:46.437030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2323edcc8a4f'
down_revision: Union[str, None] = '195fa476d19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
