"""tag column added to tasks and column name changes in revoken_tokens table

Revision ID: 2e0bf9f526bb
Revises: 4fa64a27b014
Create Date: 2025-01-27 18:15:51.308545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0bf9f526bb'
down_revision: Union[str, None] = '4fa64a27b014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revoked_tokens', sa.Column('token', sa.String(length=255), nullable=False))
    op.drop_column('revoked_tokens', 'jti')
    op.add_column('tasks', sa.Column('tag', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tag')
    op.add_column('revoked_tokens', sa.Column('jti', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('revoked_tokens', 'token')
    # ### end Alembic commands ###
