"""On delete Set Null

Revision ID: 45bfae242417
Revises: 0a72c31878cf
Create Date: 2025-01-22 23:38:12.152224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bfae242417'
down_revision: Union[str, None] = '0a72c31878cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_tag_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tags', ['tag'], ['name'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_tag_fkey', 'tasks', 'tags', ['tag'], ['name'])
    # ### end Alembic commands ###
