"""Status is now nullable=False

Revision ID: 6004a959d5e3
Revises: d6b5cbdf0ecf
Create Date: 2025-01-24 12:59:54.216369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6004a959d5e3'
down_revision: Union[str, None] = 'd6b5cbdf0ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('Pending', 'Completed', 'InProgress', 'Overdue', name='taskstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('Pending', 'Completed', 'InProgress', 'Overdue', name='taskstatus'),
               nullable=True)
    # ### end Alembic commands ###
