"""Relationship and delete mechanism cascade is changed to setnull ondelte

Revision ID: 60e932aac3d7
Revises: 2323edcc8a4f
Create Date: 2025-01-24 14:11:58.470404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e932aac3d7'
down_revision: Union[str, None] = '2323edcc8a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
