"""Second migration

Revision ID: c299d763d9dd
Revises: 8b3465b864e5
Create Date: 2025-01-23 02:03:04.316795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c299d763d9dd'
down_revision: Union[str, None] = '8b3465b864e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('Low', 'Medium', 'High', name='todo_task_priority'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('Low', 'Medium', 'High', name='todo_task_priority'),
               nullable=True)
    # ### end Alembic commands ###
