"""Python version updated and Minor schema change

Revision ID: d4d386b2007b
Revises: 2e0bf9f526bb
Create Date: 2025-01-28 01:47:08.292771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d386b2007b'
down_revision: Union[str, None] = '2e0bf9f526bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
